-- MySQL Script generated by MySQL Workbench
-- Mon Oct  5 15:33:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project1` DEFAULT CHARACTER SET utf8mb4 ;
USE `project1` ;

-- -----------------------------------------------------
-- Table `project1`.`usertype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project1`.`usertype` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  `created` DATE NOT NULL,
  `last_updated` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `project1`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project1`.`account` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `usertype_id` INT(11) NULL DEFAULT NULL,
  `created` DATE NOT NULL,
  `last_updated` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `usertype_id` (`usertype_id` ASC) VISIBLE,
  CONSTRAINT `account_ibfk_1`
    FOREIGN KEY (`usertype_id`)
    REFERENCES `project1`.`usertype` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `project1`.`persoon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project1`.`persoon` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `voornaam` VARCHAR(255) NOT NULL,
  `tussenvoegsel` VARCHAR(255) NULL DEFAULT NULL,
  `achternaam` VARCHAR(255) NOT NULL,
  `account_id` INT(11) NULL DEFAULT NULL,
  `created` DATE NOT NULL,
  `last_updated` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `account_id` (`account_id` ASC) VISIBLE,
  CONSTRAINT `persoon_ibfk_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `project1`.`account` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
